version: '3.7'
services:
  ui:
    build:
      context: web
    image: web
    ports:
      - 8888:80
    depends_on:
      - filer
  filer:
    build:
      context: filer
    image: filer
    ports:
      - 9999:9999
